#' Create meteorological criterion 
#'
#' Score a netcdf spatiotemporal dataset based on meteorological criteria.
#'
#' @importFrom stats stepfun
#'
#' @param data The path that meteorological data or a data frame generated by ERA5NetcdfToCsv or MeteoNetcdfToCsv are stored .
#' @param time_start Time (expressed in hours) of a fishing trip starts.
#' @param time_end Time (expressed in hours) of a fishing trip ends.
#' @param temp_step Temporal step of the outcome. Values: "quarter" (default), "month", "year"
#' @param diff_temp Parameter for estimating the extreme temperature Values. The default is 4 that means the extreme temperature can be 4 Co less that the max value.
#' @return Return of a data.frame.
#' @author I. Maina
#' @examples
#'
#'
#'   # Example 1
#'   library(tools4MCDA) # package for raster manipulation
#'  
#'   meteo_data<-ERA5NetcdfToCsv(nc_data = ".ERA5data.nc")
#'   meteo2017_q<-meteoCr(data = meteo_data, time_start=21, time_end=4, temp_step="quarter", diff_temp=4)
#,
#' @export


meteoCr <- function(data, time_start=21, time_end=4, temp_step="quarter", diff_temp=4) {
  
metcsv_f_nec <- data

max_temp<-max(metcsv_f_nec$t2)# check temperature range by yy...
extreme_temp<-max_temp-diff_temp

# ############_________
############___________ estimating indicators by hour and metier:
#____________GNS (gillnets), GTR( trammel nets)
#___________FPO (pots and traps?), LLS (longlines bottom)

metcsv_f_nec$SSFmeteoCr<-
  ifelse((metcsv_f_nec$ws >= 10.8), 
         0, 
         ifelse((metcsv_f_nec$t2 >= extreme_temp), #SST spikes
                0,
                ifelse((metcsv_f_nec$t2 <= 2), #SST spikes
                       0,
                       
                       ifelse((metcsv_f_nec$ws < 10.8 & metcsv_f_nec$ws >=5.5 ) & # 4-6 beaufort
                                metcsv_f_nec$tp >2.861e-06 & (metcsv_f_nec$t2 >2 & metcsv_f_nec$t2 <extreme_temp),
                              1,
                              
                              ifelse((metcsv_f_nec$ws < 10.8  & metcsv_f_nec$ws >=5.5 ) & 
                                       metcsv_f_nec$tp <2.861e-06 & (metcsv_f_nec$t2 >2 & metcsv_f_nec$t2 <extreme_temp),
                                     2,
                                     
                                     ifelse((metcsv_f_nec$ws < 5.5  & metcsv_f_nec$ws >=1.5 ) & #2-4 beaufort
                                              metcsv_f_nec$tp >=2.861e-06 & (metcsv_f_nec$t2 >2 & metcsv_f_nec$t2 <extreme_temp),
                                            3,
                                            
                                            ifelse((metcsv_f_nec$ws < 5.5  & metcsv_f_nec$ws >=1.5 ) & #< 2 beaufort
                                                     metcsv_f_nec$tp <2.861e-06 & (metcsv_f_nec$t2 >2 & metcsv_f_nec$t2 <extreme_temp),
                                                   4,
                                                   ifelse((metcsv_f_nec$ws < 1.5)& (metcsv_f_nec$t2 >2 & metcsv_f_nec$t2 <extreme_temp),#< 2 beaufort
                                                          5,
                                                          0))))))))



######_agreegate by x,y ,mm,yy to estimate mean LLS-FPO
attach(metcsv_f_nec)
time_start<-time_start
time_end<-time_end
metcsv_f_nec2<-metcsv_f_nec[-which(metcsv_f_nec$hh>time_start),]
metcsv_f_nec2<-metcsv_f_nec[-which(metcsv_f_nec$hh<time_end),]

#to make ifelse to perform estimations by year, season, quarter, month
if(temp_step=="month"){
  meteoCriterion<-(aggregate(SSFmeteoCr ~ longitude +latitude + mm + yy, FUN=mean, data=metcsv_f_nec2))
  } else if (temp_step=="year"){
    meteoCriterion<-(aggregate(SSFmeteoCr ~ longitude +latitude + yy, FUN=mean, data=metcsv_f_nec2))
  } else if (temp_step=="quarter"){
    meteoCriterion<-(aggregate(SSFmeteoCr ~ longitude +latitude + quarter+ yy, FUN=mean, data=metcsv_f_nec2))
  } else {
    meteoCriterion<-(aggregate(SSFmeteoCr ~ longitude +latitude + yy, FUN=mean, data=metcsv_f_nec2))
  }
    
return(meteoCriterion)
}
